base: /
dependencies:
  - taekwondo_mueller_sitepackage
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - typo3/form
languages:
  - title: German
    enabled: true
    locale: de_DE.utf8
    hreflang: ""
    base: /
    websiteTitle: ""
    navigationTitle: ""
    flag: de
    languageId: 0
  - title: English
    enabled: true
    locale: en_US
    hreflang: ""
    base: /en/
    websiteTitle: ""
    navigationTitle: English
    fallbackType: strict
    fallbacks: "0"
    flag: en-us-gb
    languageId: 1
rootPageId: 1
websiteTitle: ""
